#!env /bin/bash

rsync -azchP \
--exclude '/**/.tox' --exclude "/**/.git" --exclude "/**/.idea" \
--exclude "*.pyc" --exclude "*.pyd" --exclude "/**/__pycache__" \
--exclude "/**/*.egg-info" --exclude "/**/build" --exclude "/**/dist" \
--exclude "/**/.pytest_cache" --exclude "/**/.env" \
--exclude "/**/.vscode" --exclude ".DS_Store" --exclude "Thumbs.db" \
--exclude "*esktop.ini" --exclude "/**/*.code-workspace" \
--exclude "/**/sdist" $@